evaluator:
  target: !module evaluation.evaluators.composite_evaluator.CompositeEvaluator
  evaluators:
    - target: !module evaluation.evaluators.text_clip_similarity_video_evaluator.TextClipSimilarityVideoEvaluator
    - target: !module evaluation.evaluators.video_clip_similarity_video_evaluator.VideoClipSimilarityVideoEvaluator
    - target: !module evaluation.evaluators.arcface_similarity_video_evaluator.ArcfaceSimilarityVideoEvaluator
    - target: !module evaluation.evaluators.dynamic_degree_video_evaluator.DynamicDegreeVideoEvaluator
    - target: !module evaluation.evaluators.temporal_consistency_video_evaluator.TemporalConsistencyVideoEvaluator